# Server Port
server.port=8080

# Connect Gateway to Eureka Discovery Server
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Enable Automatic Routing based on Eureka Registered Microservices
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Actuator & Gateway Route Exposure
management.endpoints.web.exposure.include=health,info,metrics,gateway
management.endpoint.health.show-details=always