# Application Name
spring.application.name=jdm-config-server

# Server Port for Config Server
server.port=8888

# Active Profile set to native

#spring.profiles.active=native
#
#spring.cloud.config.server.native.search-locations=\
#  classpath:/config,\
#  classpath:/config/platform,\
#  classpath:/config/services

spring.cloud.config.server.git.uri=https://github.com/AsanI2003/jdm-expo-configurations.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

spring.cloud.config.server.git.search-paths=platform,services

# Actuator Endpoints Exposure
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always